# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c11c93466436897b10041434f93d08dea73a080309a9d0eab35d9d9f710f435e79bba9c869b4f06a5d6146924dd13d932c501b72815b0acfd670888da232c979

test:
  secret_key_base: 738648b3448f7c28c3b90fdca4ca7505196e5ff5ea9d7a7633e03a6188a4d42f745e22a554fc1efdaf98001f3d88496f0ced34e65b78548258a4bf14c25128ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
